name: Brett Peters
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections:
  projects:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
# Google Analytics
google_analytics: UA-109281829-1